name: 'PRs and issues are not accepted'

on:
  issues:
    types: opened
  pull_request:
    types: opened

jobs:
  lockdown:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/repo-lockdown@v2
        with:
          github-token: ${{ github.token }}
